services:
    solana-scraper-db:
        build:
            dockerfile: Dockerfile
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: transactions
